#!/usr/bin/env node
// Post-Vite-build housekeeping:
// - Copy invoice.css from @md-business/renderer-pdf into dist/styles/
// - Copy paged.js polyfill into dist/vendor/ (so MV3 CSP allows loading)
// - Copy the manifest already lives in public/ → dist/ via Vite's publicDir

import { mkdir, copyFile, readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const DIST = resolve(ROOT, 'dist');
const require = createRequire(import.meta.url);

async function ensureDir(p) {
  await mkdir(p, { recursive: true });
}

async function copySchemaCss() {
  const stylesDir = resolve(ROOT, '..', '..', 'packages', 'renderer-pdf', 'src', 'styles');
  const destDir = resolve(DIST, 'styles');
  await ensureDir(destDir);
  for (const file of ['invoice.css', 'spec.css', 'test-spec.css']) {
    await copyFile(resolve(stylesDir, file), resolve(destDir, file));
    console.log(`[post-build] copied ${file}`);
  }
}

async function copyPagedJs() {
  const pkgEntry = require.resolve('pagedjs');
  const pkgDir = dirname(pkgEntry);
  const candidates = [
    resolve(pkgDir, 'paged.polyfill.js'),
    resolve(pkgDir, '..', 'dist', 'paged.polyfill.js'),
    resolve(pkgDir, '..', 'paged.polyfill.js'),
  ];
  const destDir = resolve(DIST, 'vendor');
  await ensureDir(destDir);
  for (const c of candidates) {
    if (existsSync(c)) {
      await copyFile(c, resolve(destDir, 'paged.polyfill.js'));
      console.log(`[post-build] copied paged.polyfill.js from ${c}`);
      return;
    }
  }
  // Fallback: dump the contents of the pagedjs dist dir to help the user diagnose.
  const distDir = resolve(pkgDir, '..', 'dist');
  if (existsSync(distDir)) {
    const files = await readdir(distDir);
    console.warn('[post-build] paged.polyfill.js not located. dist/:', files.join(', '));
  }
  console.warn('[post-build] WARNING: paged.polyfill.js not copied — viewer pagination may regress to browser print.');
}

// CSP-safe local copy of Noto Sans JP / Noto Serif JP. We bundle the
// `japanese` and `latin` named subsets (covering JIS-1/2 kanji, kana, and
// ASCII) at the weights actually used by the invoice template and the SVG
// hanko renderer. Adding a new weight or subset is a single line in
// FONT_FILES — each line maps a fontsource file to the path served from the
// extension at runtime.
const FONT_FILES = [
  // Noto Sans JP — body text
  { pkg: '@fontsource/noto-sans-jp', file: 'noto-sans-jp-japanese-400-normal.woff2', as: 'NotoSansJP-jp-400.woff2', family: 'Noto Sans JP', subset: 'japanese', weight: 400 },
  { pkg: '@fontsource/noto-sans-jp', file: 'noto-sans-jp-japanese-700-normal.woff2', as: 'NotoSansJP-jp-700.woff2', family: 'Noto Sans JP', subset: 'japanese', weight: 700 },
  { pkg: '@fontsource/noto-sans-jp', file: 'noto-sans-jp-latin-400-normal.woff2', as: 'NotoSansJP-latin-400.woff2', family: 'Noto Sans JP', subset: 'latin', weight: 400 },
  { pkg: '@fontsource/noto-sans-jp', file: 'noto-sans-jp-latin-700-normal.woff2', as: 'NotoSansJP-latin-700.woff2', family: 'Noto Sans JP', subset: 'latin', weight: 700 },
  // Noto Serif JP — headings, formal text, and (Bold/Black) the hanko renderer
  { pkg: '@fontsource/noto-serif-jp', file: 'noto-serif-jp-japanese-400-normal.woff2', as: 'NotoSerifJP-jp-400.woff2', family: 'Noto Serif JP', subset: 'japanese', weight: 400 },
  { pkg: '@fontsource/noto-serif-jp', file: 'noto-serif-jp-japanese-700-normal.woff2', as: 'NotoSerifJP-jp-700.woff2', family: 'Noto Serif JP', subset: 'japanese', weight: 700 },
  { pkg: '@fontsource/noto-serif-jp', file: 'noto-serif-jp-japanese-900-normal.woff2', as: 'NotoSerifJP-jp-900.woff2', family: 'Noto Serif JP', subset: 'japanese', weight: 900 },
  { pkg: '@fontsource/noto-serif-jp', file: 'noto-serif-jp-latin-400-normal.woff2', as: 'NotoSerifJP-latin-400.woff2', family: 'Noto Serif JP', subset: 'latin', weight: 400 },
  { pkg: '@fontsource/noto-serif-jp', file: 'noto-serif-jp-latin-700-normal.woff2', as: 'NotoSerifJP-latin-700.woff2', family: 'Noto Serif JP', subset: 'latin', weight: 700 },
];

// Unicode-range descriptors for `@font-face` so the browser only downloads the
// subset matching the rendered text. Mirrors fontsource's published ranges.
const SUBSET_RANGES = {
  latin: 'U+0000-007F,U+00A0-00FF,U+0152-0153,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  japanese:
    'U+3000-30FF,U+3131-318E,U+31F0-31FF,U+4E00-9FFF,U+F900-FAFF,U+FF00-FFEF,U+1B000-1B0FF,U+1F100-1F2FF',
};

async function copyFonts() {
  const fontsDir = resolve(DIST, 'vendor', 'fonts');
  await ensureDir(fontsDir);
  const css = [];
  css.push('/* AUTO-GENERATED by scripts/post-build.mjs — do not edit. */');
  css.push('/* Sources:');
  css.push(' *   Noto Sans JP, Noto Serif JP — SIL Open Font License 1.1');
  css.push(' *   https://github.com/notofonts/noto-cjk  via @fontsource/* npm packages');
  css.push(' */');
  for (const { pkg, file, as, family, subset, weight } of FONT_FILES) {
    const entry = require.resolve(`${pkg}/files/${file}`);
    await copyFile(entry, resolve(fontsDir, as));
    css.push('@font-face {');
    css.push(`  font-family: "${family}";`);
    css.push('  font-style: normal;');
    css.push('  font-display: swap;');
    css.push(`  font-weight: ${weight};`);
    css.push(`  src: url("../vendor/fonts/${as}") format("woff2");`);
    css.push(`  unicode-range: ${SUBSET_RANGES[subset]};`);
    css.push('}');
  }
  // Brand alias families used by the hanko/SVG renderer so downstream CSS can
  // swap a forked font without touching every callsite.
  css.push('/* Alias families — fork-friendly. Override these @font-face blocks');
  css.push('   in a custom build to swap a tensho or kaisho font in place. */');
  css.push('@font-face { font-family: "MdBusiness Body"; src: local("Noto Sans JP"), local("Hiragino Sans"); }');
  css.push('@font-face { font-family: "MdBusiness Stamp"; src: local("Noto Serif JP"), local("Yu Mincho"); font-weight: 900; }');
  const cssPath = resolve(DIST, 'styles', 'fonts.css');
  await ensureDir(dirname(cssPath));
  await writeFile(cssPath, css.join('\n') + '\n', 'utf8');
  console.log(`[post-build] copied ${FONT_FILES.length} font files and wrote styles/fonts.css`);
}

// Built-in starter templates — copied into `dist/templates/<schema>/` so the
// popup can offer "Start from a template" without needing the user to bring
// their own .md. Listed explicitly (not glob) so each entry is reviewable in
// diff before being shipped to the Web Store.
const STARTER_TEMPLATES = [
  {
    schema: 'invoice',
    category: '適格請求書',
    file: 'standard-ja.md',
    label: '日本語フィールド名・適格請求書（推奨）',
    description: '日本語キー（請求書番号 / 発行元 / 品目 …）の最新スタイル。3 品目 + 振込先 + 印影。',
  },
  {
    schema: 'invoice',
    category: '適格請求書',
    file: 'standard.md',
    label: '英語フィールド名・標準請求書',
    description: '英語キー（invoiceNumber / issuer / items …）の標準スタイル。',
  },
  {
    schema: 'invoice',
    category: '適格請求書',
    file: 'inbound-eligible.md',
    label: '英語フィールド名・軽減税率（8%）込み',
    description: '8% 軽減税率対象品目を含む適格請求書サンプル。',
  },
  {
    schema: 'invoice',
    category: '免税事業者',
    file: 'tax-exempt-ja.md',
    label: '日本語フィールド名・免税事業者向け',
    description: '適格請求書発行事業者でない個人事業主・小規模法人向け。登録番号なしで「免税事業者: true」を指定。経過措置案内を自動出力。',
  },
  {
    schema: 'spec',
    category: '基本設計書',
    file: 'standard-ja.md',
    label: '日本語フィールド名・基本設計書（EC 注文管理サブシステム）',
    description: '8 章 / Mermaid 図 / 表を含む数ページの基本設計書サンプル。日本語キー（文書番号 / 作成者 / レビュアー …）。',
  },
  {
    schema: 'test-spec',
    category: '検証シート',
    file: 'standard-ja.md',
    label: '日本語フィールド名・検証シート（ログイン機能サンプル）',
    description: '列定義（プルダウン / 日付 / 数値）と検証手順表を含む検証シート。Google Sheets 連携 + GitHub 自動同期に対応。日本語キー。',
  },
];

// Display order for category sections in the popup. Templates whose category
// is not listed here fall back to the end (preserves insertion order).
const CATEGORY_ORDER = ['適格請求書', '免税事業者', '基本設計書', '検証シート'];

async function copyStarterTemplates() {
  const repoRoot = resolve(ROOT, '..', '..');
  const manifest = [];
  // Sort so categories appear in CATEGORY_ORDER while preserving insertion
  // order within each category (and after that, unknown categories).
  const sorted = [...STARTER_TEMPLATES].sort((a, b) => {
    const ai = CATEGORY_ORDER.indexOf(a.category);
    const bi = CATEGORY_ORDER.indexOf(b.category);
    const av = ai === -1 ? CATEGORY_ORDER.length : ai;
    const bv = bi === -1 ? CATEGORY_ORDER.length : bi;
    return av - bv;
  });
  for (const t of sorted) {
    const src = resolve(repoRoot, 'templates', t.schema, t.file);
    const destDir = resolve(DIST, 'templates', t.schema);
    await ensureDir(destDir);
    await copyFile(src, resolve(destDir, t.file));
    manifest.push({
      schema: t.schema,
      category: t.category,
      file: t.file,
      label: t.label,
      description: t.description,
      path: `templates/${t.schema}/${t.file}`,
    });
  }
  // NOTE: file name is `index.json`, not `manifest.json`. Chrome Web Store's
  // package validator scans for *any* manifest.json under the zip root and
  // rejects the upload with "複数のマニフェストが見つかりました" when a second
  // one exists at templates/manifest.json. Keep this file named index.json.
  const manifestPath = resolve(DIST, 'templates', 'index.json');
  await writeFile(manifestPath, JSON.stringify({ templates: manifest }, null, 2) + '\n', 'utf8');
  console.log(`[post-build] copied ${STARTER_TEMPLATES.length} starter templates and wrote templates/index.json`);
}

await copySchemaCss();
await copyPagedJs();
await copyFonts();
await copyStarterTemplates();
console.log('[post-build] done.');
